# Generated by Django 2.2.28 on 2024-03-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('totalPosts', models.IntegerField(default=0)),
                ('totalLikes', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('isAI', models.BooleanField(default=False)),
                ('file', models.ImageField(upload_to='images/')),
                ('likes', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField()),
                ('nameSlug', models.SlugField()),
                ('slashSlug', models.CharField(default='null', max_length=128)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artecho.Category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artecho.Image')),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('profilePicture', models.ImageField(default='images/blank_pfp.png', upload_to='profilePics/')),
                ('bio', models.TextField(max_length=1000)),
                ('totalLikes', models.IntegerField(default=0)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('liked', models.ManyToManyField(default=None, to='artecho.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
