# Generated by Django 2.2.28 on 2024-03-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(upload_to='profilePics/'),
        ),
    ]
