# Generated by Django 2.2.28 on 2024-03-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0002_auto_20240303_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surename',
            new_name='surname',
        ),
    ]
