# Generated by Django 2.2.28 on 2024-03-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0002_image_slashslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nameSlug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
