# Generated by Django 2.2.28 on 2024-03-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0003_auto_20240303_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forename',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
