# Generated by Django 2.2.28 on 2024-03-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0004_auto_20240303_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='artecho.Image'),
        ),
    ]
