# Generated by Django 2.2.28 on 2024-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0006_auto_20240304_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
