# Generated by Django 2.2.28 on 2024-03-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0008_auto_20240304_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artecho.Image'),
        ),
    ]
