# Generated by Django 2.2.28 on 2024-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0010_auto_20240304_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
