# Generated by Django 2.2.28 on 2024-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0011_auto_20240304_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='isAI',
            field=models.BooleanField(default=False),
        ),
    ]
