# Generated by Django 2.2.28 on 2024-03-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0012_auto_20240304_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artecho.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artecho.User'),
        ),
    ]
