# Generated by Django 2.2.28 on 2024-03-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0015_auto_20240316_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
