# Generated by Django 2.2.28 on 2024-03-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artecho', '0015_auto_20240321_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_like', to='artecho.User'),
        ),
    ]
