# Generated by Django 5.0.1 on 2024-03-18 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artecho", "0017_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
