# Generated by Django 5.0.1 on 2024-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artecho", "0020_alter_image_poster_userprofile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
