# Generated by Django 5.0.1 on 2024-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artecho", "0021_userprofile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
